sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.8.3
before_install:
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-ce
script:
  - make docker-build
notifications:
  email:
    recipients:
      - harsh@portworx.com
    on_success: always
    on_failure: always
