FROM golang:1.9.1
MAINTAINER harsh@portworx.com

RUN mkdir -p /go/src/github.com/harsh-px/px-operator

RUN go get "k8s.io/apimachinery/pkg/apimachinery/registered"

WORKDIR /go/src/github.com/harsh-px/px-operator
